### PR TITLE
Adds: fixed positioning, disabled items, loading indicator, and programmatic methods

### PR DESCRIPTION
**Pull request by cgross**
Hi,

We started experimenting with quill-mention recently.  We were using other solutions but we encountered tons of issues so we began looking for another library.  This library was the best one we found and we're really excited to switch over to it.  But we also have a complex application and needed a bunch of extra functionality.  So we added it and are submitting this for your review.  

This PR adds:
* Fixed positioning - allows the menu to be appended to the body instead of the quill container.  Our app puts the quill editor in a list with overflow:auto which meant the menu was usually hidden.
* Disabled items - We have complex menus that show group headers, information text, and similar items in addition to the regular selectable items.  So we added a feature to add items that are "disabled".  A disabled item doesn't ever get selected  with the keyboard or mouse.  So you can add disabled items, use the renderItem function to do whatever you want with them.  We added an example to the demo app to show it being used for group headers.
* Loading indicator - For asynchronous loading, a menu item. that shows and a corresponding renderLoading method to allow users to style it.  We also had to fix an issue where many consecutive source() calls could overwrite each other if a earlier source() call finished after a more recent call.
* Programmatic methods - We need the ability to insert mentions and trigger the menu programmatically.  So we added methods and documented them in the README.

We're happy to make changes on any of the implementation as necessary.  We updated the demo app to have a second example that shows some of these advanced features.

-Chris

### CODE REVIEW

**Comment by MadSpindel** [comment]
Are you using prettier? Looks like the code have been formatted with something else. Could you adress that? Then it will be much easier to do the code review, thank you 👍

**Comment by cgross** [comment]
I was using prettier but with different settings.  I tried to reformat it as best I could.  Should be very few formatting differences now.

I also added one more feature.  The ability to customize the allowedChars by denotationChar by provided a function instead the static regex.  Our product needed to prevent spaces in hashtags as is typical but allow them in user mentions.

**Comment by elishaterada** [comment]
+1 This change is much appreciated, especially a fixed positioning.

**Comment by MadSpindel** [comment]
@cgross Are you sure you are using prettier? And if so, could you add your config to the repo so everyone uses the same?

**Comment by cgross** [comment]
@MadSpindel I'm using prettier plugin for VS Code with it configured in the settings instead of a separate file.  Maybe we could move on to talking about the meat of the pull request.

**Comment by MadSpindel** [comment]
Sorry if I'm picky but it's more about making the code review (and future code reviews) easier to read without the all code formatting changes. I will try to code review it tomorrow, and I guess my prettier will overwrite yours.

**Review by MadSpindel — APPROVED** [review]
This looks really good to me. Thank you @cgross for the excellent job!

**Comment by elishaterada** [comment]
@cgross I just used the v3.0.0 and the fixed positioning works, thanks so much!

**Pull request merged**
