### PR TITLE
Add or remove className bottom or top without loop

### PR DESCRIPTION
**Pull request by KoAi**
This PR aimed to simplify classList management and have better performance

Closes afry#135

### CODE REVIEW

**Comment by MadSpindel** [comment]
It's seems like it was introduced in PR #129 allowing multiple class names and your fix seems to remove the possibility to have multiple class names?

**Comment by KoAi** [comment]
@MadSpindel you are right, sorry I have not seen this possibility. I commit a new fix to make it working for both simple class name and multiple class names (noted that previously It was not working correctly even with with multiple).

It should do the job now.

**Comment by MadSpindel** [comment]
Thank you!

**Comment by KoAi** [comment]
Thanks

**Comment by gmoratorio** [comment]
Thanks for this release. Note that in `2.2.4` which was utilizing  forEach, it was causing issues in IE11. `Object` doesn't support property or method 'forEach'` Looks like the `2.2.5` changes fix it 👍

**Pull request merged**
